#!/bin/bash
# Fetch the brainjar CLI markdown reference at build time and drop
# each page into src/content/docs/reference/cli/ with Starlight-
# compatible frontmatter. Runs as part of predev / prestart / build
# so the site always reflects the current release.
#
# Source of truth: https://get.brainjar.sh/brainjar/<tag>/docs.tar.gz,
# which is produced by the brainjar release workflow from the
# freshly-built release binary via `brainjar docs`. Filenames in the
# tarball use underscores (cobra/doc's GenMarkdownTree convention).
#
# The landing site never reads a local brainjar binary. Staging
# against unreleased CLI changes requires cutting a prerelease tag
# on the brainjar repo and setting BRAINJAR_DOCS_TAG here.
set -e

OUT="src/content/docs/reference/cli"
TAG="${BRAINJAR_DOCS_TAG:-latest}"

if [ "$TAG" = "latest" ]; then
    TAG="$(curl -fsSL 'https://get.brainjar.sh/brainjar/latest')"
fi

echo "Syncing CLI docs for ${TAG} into ${OUT}"

# Clean slate on every run so files removed from the CLI don't linger
# as orphan pages.
rm -rf "$OUT"
mkdir -p "$OUT"

# Extract the tarball directly from the fetch pipe into OUT. Tarball
# entries sit at the root (no top-level dir inside the archive).
curl -fsSL "https://get.brainjar.sh/brainjar/${TAG}/docs.tar.gz" | tar xz -C "$OUT"

# Post-process each markdown file so Starlight can render it:
#   1. Prepend YAML frontmatter with a `title:` derived from the first
#      "## " heading (cobra emits H2 as the command name).
#   2. Strip the auto-generated footer ("###### Auto generated by ..."),
#      which adds visual noise and embeds a timestamp that causes
#      spurious git diffs.
#   3. Rewrite internal `[text](brainjar_foo.md)` links to relative
#      slug form so Starlight's link resolver finds them.
for f in "$OUT"/*.md; do
    name="$(basename "$f" .md)"

    # Title from first "## " heading.
    title="$(grep -m 1 '^## ' "$f" | sed 's/^## //')"
    if [ -z "$title" ]; then
        # Fallback: filename with underscores → spaces.
        title="$(echo "$name" | tr '_' ' ')"
    fi

    # Strip the auto-generated footer line and any blank line
    # immediately preceding it.
    sed -i '/^###### Auto generated by /d' "$f"
    # Collapse trailing blank lines.
    sed -i -e :a -e '/^$/{$d;N;ba' -e '}' "$f"

    # Rewrite relative .md links to slug paths. cobra emits
    # `[foo](brainjar_foo.md)`; Starlight prefers `(./brainjar_foo/)`.
    sed -i 's|\](brainjar\([^)]*\)\.md)|](./brainjar\1/)|g' "$f"

    # Prepend frontmatter in-place.
    tmp="$(mktemp)"
    {
        printf -- '---\n'
        printf 'title: %s\n' "$title"
        printf -- '---\n\n'
        cat "$f"
    } > "$tmp"
    mv "$tmp" "$f"
done

# Rename the root index from brainjar.md → index.md so the default
# /reference/cli/ route lands on it. Starlight treats index.md as
# the directory's landing page.
if [ -f "$OUT/brainjar.md" ]; then
    mv "$OUT/brainjar.md" "$OUT/index.md"
fi

echo "Synced $(ls "$OUT" | wc -l) CLI reference pages"
