#!/bin/bash
# Fetch the brainjar CLI markdown reference at build time and
# consolidate every command into a single Starlight page at
# src/content/docs/reference/cli.md — matching the shape of the
# pre-autogen hand-written reference.
#
# Source of truth: https://get.brainjar.sh/brainjar/<tag>/docs.tar.gz,
# produced by the brainjar release workflow from the freshly-built
# release binary via `brainjar docs`. cobra's GenMarkdownTree emits
# one file per command; this script merges them into a single page
# grouped by top-level command, with SEE ALSO cross-links and the
# auto-generated timestamp footer stripped.
#
# The landing site never reads a local brainjar binary. Staging
# against unreleased CLI changes requires cutting a prerelease tag
# on the brainjar repo and setting BRAINJAR_DOCS_TAG here.
set -e

# .mdx so the Starlight <Aside> component at the top actually
# renders — plain .md files treat JSX imports as text.
OUT="src/content/docs/reference/cli.mdx"
TAG="${BRAINJAR_DOCS_TAG:-latest}"

if [ "$TAG" = "latest" ]; then
    TAG="$(curl -fsSL 'https://get.brainjar.sh/brainjar/latest')"
fi

echo "Syncing CLI docs for ${TAG} into ${OUT}"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

curl -fsSL "https://get.brainjar.sh/brainjar/${TAG}/docs.tar.gz" | tar xz -C "$STAGE"

# Build the consolidated page in-place. Sections flow as:
#   frontmatter → global synopsis → per-command sections.
# Top-level commands become `## <name>`; subcommands become
# `### <name> <sub>`. Each section shows description, usage code
# block, examples (if present), and flag blocks — but never the
# cobra-emitted SEE ALSO section or the auto-generated footer.
mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp)"

cat <<EOF > "$TMP"
---
title: CLI Reference
description: Complete reference for every brainjar command, autogenerated from the ${TAG} release.
---

import { Aside } from '@astrojs/starlight/components';

<Aside type="tip">
  This page is autogenerated from the \`brainjar\` binary shipped in
  each release. To preview docs for an unreleased change, cut a
  prerelease tag on the brainjar repo and set \`BRAINJAR_DOCS_TAG\`
  when rebuilding the site.
</Aside>

EOF

# extract_section strips a single markdown section out of the page
# emitted by cobra and reshapes its code blocks. $1 is the source
# file; $2 is a heading bump (0 or 1). Internal `### Heading` lines
# are bumped by that many hashes so nesting stays consistent below
# the command heading the caller wrote.
#
# Transforms applied:
#   - `## brainjar ...` opening heading is dropped (caller writes its own)
#   - `### SEE ALSO` and everything after it is dropped
#   - auto-generated-by trailer is dropped
#   - Plain ``` fences outside the Options sections become ```bash
#   - Code blocks inside `Options` / `Options inherited from parent
#     commands` sections become markdown tables with one row per flag
extract_section() {
    local src="$1"
    local bump="${2:-0}"
    awk -v bump="$bump" '
        function bumped_heading(line) {
            prefix = ""
            for (i = 0; i < bump; i++) prefix = prefix "#"
            return prefix line
        }

        /^###### Auto generated by / { next }

        /^## brainjar/ {
            skip_next_blank = 1
            next
        }
        skip_next_blank == 1 && /^$/ {
            skip_next_blank = 0
            next
        }

        /^### SEE ALSO/ { exit }

        # Drop the "Options inherited from parent commands" section
        # from every command page. The global --home/--json flags are
        # documented once in the Overview; repeating them per command
        # is 69 copies of the same two rows.
        /^###+ Options inherited from parent commands/ {
            suppress = 1
            next
        }
        # A new heading lifts the suppression.
        /^###+ / && suppress {
            suppress = 0
        }
        suppress { next }

        # Synopsis section — drop the heading and render the body as
        # a blockquote instead. cobra emits Synopsis as the long-form
        # prose description; making it a quote visually distinguishes
        # it from the lead sentence above without adding a redundant
        # "Synopsis" label to the TOC.
        #
        # Interior blank lines become blockquote-blank (`>`). Trailing
        # blank lines between the last prose paragraph and whatever
        # follows (usually the usage code fence) are buffered so we
        # can drop them — otherwise the page ends every Synopsis
        # with an orphan `>` that renders as an empty quote line.
        /^###+ Synopsis$/ {
            in_synopsis = 1
            synopsis_seen_body = 0
            synopsis_pending_blanks = 0
            section = "Synopsis"
            next
        }
        in_synopsis && /^$/ {
            # Leading blanks (before any body) are eaten; interior
            # blanks are buffered as pending and flushed only when
            # we see more body.
            if (synopsis_seen_body) synopsis_pending_blanks++
            next
        }
        # End of Synopsis block: the next heading or a fenced block
        # closes it. Pending blanks are discarded — they were
        # trailing.
        in_synopsis && (/^#+ / || /^```/) {
            in_synopsis = 0
            synopsis_pending_blanks = 0
            # Fall through to normal handling of the closing line.
        }
        in_synopsis {
            # Flush buffered blanks as blockquote-blank lines now that
            # we have more content behind them.
            while (synopsis_pending_blanks > 0) {
                print ">"
                synopsis_pending_blanks--
            }
            print "> " $0
            synopsis_seen_body = 1
            next
        }

        # Heading lines: track the current section (for flag-table
        # detection) and bump heading depth if the caller asked.
        /^###+ / {
            section = $0
            sub(/^###+ /, "", section)
            if (bump > 0) {
                print bumped_heading($0)
            } else {
                print
            }
            next
        }

        # Start of a fenced block.
        /^```/ && !in_fence {
            in_fence = 1
            # Decide whether this is an Options table or a shell block
            # based on the most recent heading we saw.
            is_opts = (section ~ /^Options/) ? 1 : 0
            if (is_opts) {
                # Open a markdown table instead of a code fence; defer
                # the header row until we have at least one body row,
                # so a table with only `-h, --help` (which we drop
                # below) does not leave an empty table behind.
                opts_header_pending = 1
            } else {
                print "```bash"
            }
            next
        }

        # End of a fenced block.
        /^```/ && in_fence {
            in_fence = 0
            if (!is_opts) print "```"
            is_opts = 0
            opts_header_pending = 0
            next
        }

        # Inside a code fence.
        in_fence {
            if (is_opts) {
                line = $0
                sub(/^[ \t]+/, "", line)
                if (line == "") next
                # Parse "flag spec  description" with 2+ spaces between.
                if (match(line, /  +/) > 0) {
                    flag = substr(line, 1, RSTART - 1)
                    desc = substr(line, RSTART + RLENGTH)
                } else {
                    flag = line
                    desc = ""
                }
                # Drop the universal -h/--help row from every command.
                if (flag == "-h, --help") next
                # Emit the table header on first body row.
                if (opts_header_pending) {
                    print "| Flag | Description |"
                    print "|------|-------------|"
                    opts_header_pending = 0
                }
                gsub(/\|/, "\\|", desc)
                printf "| `%s` | %s |\n", flag, desc
            } else {
                # Strip a single leading 2-space indent. cobra takes
                # its Example: field verbatim from the Go source,
                # where examples are typically indented to line up
                # with surrounding code; that indent is preserved
                # inside the markdown fence and makes the rendered
                # block look tabbed.
                sub(/^  /, "")
                print
            }
            next
        }

        { print }
    ' "$src" | awk '
        # Second pass — drop any `### Heading` whose body is empty
        # after the first pass stripped -h/--help and the inherited-
        # options section. Buffers each heading plus its following
        # lines until the next heading (or EOF); emits only if the
        # buffer contains at least one non-blank, non-rule line.

        function flush() {
            if (pending && has_body) {
                print pending
                for (i = 0; i < n; i++) print buf[i]
            }
            pending = ""
            n = 0
            has_body = 0
        }

        # Any heading (H2 / H3 / H4) marks the start of a new section.
        /^#+ / {
            flush()
            pending = $0
            next
        }

        # Non-heading lines buffer under the current pending heading.
        pending {
            buf[n++] = $0
            if ($0 != "" && $0 !~ /^---+$/) has_body = 1
            next
        }

        { print }

        END { flush() }
    ' | awk '
        # Third pass — escape angle-bracket placeholders outside code
        # fences so MDX does not try to parse them as JSX. Wraps
        # `<slug>`, `<name>`, etc. in backticks, which renders as
        # inline code in the final HTML.
        #
        # Runs only on non-fenced lines; inside fenced blocks the
        # placeholders already render literally.
        #
        # Implementation: each match replaces the tag in-place with
        # sentinel bytes (\001 for "<", \002 for ">") so the next
        # iteration of `match()` does not re-discover the same tag
        # and loop forever. A final gsub restores the sentinels to
        # real angle brackets before we print.

        /^```/ { in_fence = !in_fence; print; next }
        in_fence { print; next }
        {
            while (match($0, /<[a-zA-Z][a-zA-Z0-9_-]*>/)) {
                before = substr($0, 1, RSTART - 1)
                tag = substr($0, RSTART, RLENGTH)
                after = substr($0, RSTART + RLENGTH)
                # Strip the leading "<" and trailing ">" from tag so
                # we can rebuild with sentinel bytes instead.
                inner = substr(tag, 2, length(tag) - 2)
                if (substr(before, length(before)) == "`") {
                    # Already wrapped in backticks (cobra edge case or
                    # re-run) — just sentinel-mark to move past.
                    $0 = before "\001" inner "\002" after
                } else {
                    $0 = before "`\001" inner "\002`" after
                }
            }
            gsub(/\001/, "<", $0)
            gsub(/\002/, ">", $0)
            # Escape `{` outside code fences — MDX treats braces as
            # JSX expression boundaries, so a literal `${fpath[1]}`
            # from a zsh example throws `ReferenceError: fpath is
            # not defined` at render time. Backslash-escape every
            # open brace; MDX accepts `\{` as a literal `{`.
            gsub(/\{/, "\\{", $0)
            print
        }
    '
}

# Emit the top-level brainjar.md as the opening prose so readers
# get an overview before the per-command tables. The Options heading
# inside that section is demoted so it doesn't clutter the page's
# right-side TOC with an entry that's redundant with the lead
# callout — the flags shown there are global and apply to every
# command below, which is why per-command sections don't repeat them.
if [ -f "$STAGE/brainjar.md" ]; then
    {
        echo "## Overview"
        echo
        extract_section "$STAGE/brainjar.md" | \
            sed -e 's/^### Options$/**Global options**/'
        echo
        echo "> The options above are global — they apply to every command below."
        echo
        echo "---"
        echo
    } >> "$TMP"
fi

# Walk commands in plain lexicographic order. That naturally puts
# each umbrella page (`brainjar_soul.md`) before its subcommands
# (`brainjar_soul_create.md`, `brainjar_soul_list.md`, …) because
# the umbrella sorts before any longer underscore-suffixed sibling.
find "$STAGE" -maxdepth 1 -name 'brainjar_*.md' -printf '%f\n' | LC_ALL=C sort | \
    while read -r name; do
        base="${name%.md}"
        # Strip the redundant "brainjar " prefix from the heading.
        # The entire page is about brainjar — nav entries and the page
        # TOC read cleaner as e.g. `soul use` instead of
        # `brainjar soul use`. Top-level umbrellas become single-word
        # headings (`soul`, `shell`); subcommand headings drop just
        # the leading "brainjar" while keeping the parent command for
        # both context and anchor uniqueness (`soul use`, not `use`,
        # which would collide with every other `use` subcommand).
        heading="$(echo "$base" | tr '_' ' ' | sed -e 's/^brainjar //')"
        # Depth drives heading level AND the bump we pass to
        # extract_section so internal "### Synopsis/Options" headings
        # always sit one level below the command heading:
        #   brainjar_soul (depth 1) → ## heading, internal ### stays
        #   brainjar_soul_create  (depth 2) → ### heading, internal ### bumped to ####
        depth=$(awk -F'_' '{print NF-1}' <<< "$base")
        if [ "$depth" -le 1 ]; then
            hash="##"
            hr=1
            # Leaf top-level commands (no subcommand siblings) bump
            # internal Examples/Options from ### to #### so they render
            # identically to subcommand sections. Umbrella commands
            # keep bump=0 because their children already occupy ###.
            if compgen -G "$STAGE/${base}_*.md" > /dev/null; then
                bump=0
            else
                bump=1
            fi
        else
            hash="###"
            bump=1
            hr=0
        fi

        {
            echo "$hash $heading"
            echo
            extract_section "$STAGE/$name" "$bump"
            echo
            [ "$hr" = "1" ] && { echo "---"; echo; } || true
        } >> "$TMP"
    done

mv "$TMP" "$OUT"
echo "Wrote ${OUT}"
